### ISSUE TITLE
Bug in ``weighted_fingerprint`` bit shift and operator precedence

### ISSUE THREAD

**Issue by rmax** [scrapinghub/python-simhash#2]
The function `weighted_fingerprint` has two bugs in the [line 120](https://github.com/scrapinghub/python-simhash/blob/master/simhash/_simhash.c#L120):

``` c11
        result |= ((PY_LONG_LONG)(sums[i] > ALMOST_0)) << i;
```
1. The shift should be `<< 1`.
2. Given the operator `<<` have precedence over `|`, it doesn't achieve the expected result.

PR: https://github.com/scrapinghub/python-simhash/pull/1

**Comment by plafl** [comment]
I don't think any of the above points is valid:
1. We want to set the i-th bit of result if sums[i] is positive. Imagine long long has 8 bits (instead of the most probable 64 bits for long long). If sums = {-0.5, 0.1, -0.2, 0.3, 0.4, -0.1, 4.1, 0.1} then result must be 01011011. Result is built by doing:
   
   ```
    result = 00000000 |  // (sums[7] > 0) << 7
             01000000 |  // (sums[6] > 0) << 6
             00000000 |  // (sums[5] > 0) << 5
             00010000 |  // (sums[4] > 0) << 4
             00001000 |  // (sums[3] > 0) << 3
             00000000 |  // (sums[2] > 0) << 2
             00000010 |  // (sums[1] > 0) << 1
             00000001;   // (sums[0] > 0) << 0
   ```
2. The right side of an assignment is always evaluated first, and so operator precedence does not apply. Imagine the following transformation:
   
   ```
    result |= expression --> result = result | (expression)
   ```

**Comment by rmax** [comment]
Thanks @plafl. I just figured out my confusion was between these two expressions:

```
        result = result | ((sums[i] > ALMOST_0) << i);
```

and

```
        result = (result | (sums[i] > ALMOST_0))) << 1;
```

Both build a long representation of the bit array, although the last one uses one more bit as verified in the code below:

```
bits = '10010011'
n = len(bits)

x = 0
for i, b in enumerate(bits):
    x = x | ((b == '1') << i) 

y = 0
for b in bits:
    y = (y | (b == '1')) << 1

print bin(x)  # 0b11001001
print bin(y)  # 0b100100110
```

The latter method is used in the `fingerprint` function https://github.com/scrapinghub/python-simhash/blob/master/simhash/_simhash.c#L70.
